# Generated by Django 3.2.18 on 2023-06-26 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fbd_app', '0002_event_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='event_dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
